# Generated by Django 5.0.3 on 2024-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
